//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkValonTila
    {
        public int IdValonTila { get; set; }
        public string HuoneNimi { get; set; }
        public string ValaisinNimi { get; set; }
        public Nullable<System.DateTime> ValotOn33 { get; set; }
        public bool Valot33 { get; set; }
        public Nullable<System.DateTime> ValotOn66 { get; set; }
        public bool Valot66 { get; set; }
        public Nullable<System.DateTime> ValotOn100 { get; set; }
        public bool Valot100 { get; set; }
        public Nullable<System.DateTime> ValotOff { get; set; }
        public bool ValonTilaOff { get; set; }
    }
}
